# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 11:05
from __future__ import unicode_literals

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('id_number', models.CharField(max_length=16)),
                ('phone_number', models.CharField(max_length=16)),
                ('email_address', models.EmailField(max_length=254)),
                ('physical_address', models.TextField(blank=True, max_length=128)),
                ('headshot_image', models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path, verbose_name='Customer Photo')),
                ('residence_image', models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path, verbose_name='Proof of residence')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path, verbose_name='Customer Signature')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
